services:
  - type: web
    name: vendure
    env: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: yarn install && yarn build
    startCommand: yarn start:prod
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: vendure-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: vendure-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: vendure-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: vendure-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: vendure-db
          property: database
      - key: NODE_ENV
        value: production
      - key: APP_SECRET
        generateValue: true
databases:
  - name: vendure-db
    plan: starter
